services:
  pgadmin:
    image: dpage/pgadmin4
    ports:
      - 5000:80
    environment:
      # use hostname host.docker.internal to connect instead of localhost
      # and use db user "knex"
      PGADMIN_DEFAULT_EMAIL: admin@lynx.rest
      PGADMIN_DEFAULT_PASSWORD: password
  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
