services:
  keycloak:
    image: jboss/keycloak
    ports:
      - 8080:8080
    volumes:
      - ../keycloak.json:/mnt/keycloak.json
    environment:
      DB_VENDOR: H2
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: password
      KEYCLOAK_IMPORT: /mnt/keycloak.json
  reverse-proxy:
    image: caddy:alpine
    ports:
      - 1443:443
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ../caddy:/config
  pgweb:
    image: sosedoff/pgweb
    ports:
      - 8081:8081
    volumes:
      - ../../scripts/wait-for.sh:/mnt/wait-for.sh
    environment:
      - DATABASE_URL=postgres://knex@postgres/blink?sslmode=disable
    depends_on:
      - postgres
    command:
      - /mnt/wait-for.sh
      - postgres:5432
      - --
      - /usr/bin/pgweb
      - --bind=0.0.0.0
      - --listen=8081
