$id: Link
type: object
properties:
  id:
    type:
      - integer # id is an integer internally, but
      - string # is exposed as a hash externally
    readOnly: true
  creatorId:
    $ref: User#/properties/id
  hash:
    type: string
    nullable: true
    minLength: 4
    maxLength: 25
    pattern: "\\w+"
  originalUrl:
    type: string
    readOnly: true
  shortenedUrl:
    type: string
    readOnly: true
  brandedUrl:
    type: string
    nullable: true
    readOnly: true
  meta:
    type: object
    properties:
      author:
        type: string
        nullable: true
      date:
        type: string
        nullable: true
        format: date
      description:
        type: string
        nullable: true
      lang:
        type: string
        nullable: true
      logo:
        type: string
        nullable: true
        format: uri
      publisher:
        type: string
        nullable: true
      title:
        type: string
        nullable: true
    additionalProperties: false
  # these will get overwritten by default timestamps anyway
  createdAt:
    type: string
    format: date-time
    readOnly: true
  updatedAt:
    type: string
    format: date-time
    readOnly: true
required: # null vs. undefined
  - originalUrl
additionalProperties: false
