version: 2.1

orbs:
  node: circleci/node@5
  slack: circleci/slack@4

aliases:
  - &runner
    executor:
      name: node/default
      tag: lts
  - &size
    resource_class: medium

jobs:
  lint:
    <<: *runner
    <<: *size
    steps:
      - checkout
      - node/install-packages
      - run: npm run lint:prettier
      - run: npm run lint:eslint -- --format junit --output-file reports/eslint/results.xml
  test-frontend:
    <<: *runner
    <<: *size
    steps:
      - checkout
      - node/install-packages
      - run: npm run pretest
      - run:
          command: npm run test:nowatch:frontend -- -- --ci --reporters=jest-junit --reporters=default
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/jest-frontend
  test-backend:
    <<: *size
    docker:
      - image: cimg/node:lts
        environment:
          NODE_ENV: test
          DATABASE_URL: postgres://knex@localhost/blink
          REDIS_URL: redis://localhost
      - image: circleci/postgres:alpine-ram
        environment:
          POSTGRES_DB: blink
          POSTGRES_USER: knex
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: circleci/redis:alpine
    steps:
      - checkout
      - node/install-packages
      - run: npm run pretest
      - run:
          command: npm run test:nowatch:backend -- --ci --reporters=jest-junit --reporters=default
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/jest-backend
            LINK_TIMEOUT: 4 seconds
  publish-tag:
    machine:
      image: ubuntu-2004:202107-02
    resource_class: small
    steps:
      - checkout
      - &docker-login
        run: echo $GHCR_TOKEN | docker login ghcr.io -u JaneJeon --password-stdin
      - run: docker build -t "ghcr.io/janejeon/blink:$CIRCLE_TAG" .
      - run: docker push "ghcr.io/janejeon/blink:$CIRCLE_TAG"
  publish-latest:
    machine:
      image: ubuntu-2004:202107-02
    resource_class: small
    steps:
      - checkout
      - *docker-login
      - run: docker build -t "ghcr.io/janejeon/blink:latest" .
      - run: docker push "ghcr.io/janejeon/blink:latest"

workflows:
  build-and-test:
    jobs:
      - lint:
          post-steps:
            - &retrieve-junit
              store_test_results:
                path: reports
      - test-frontend: &test-config
          context: shared-vars
          requires:
            - lint
          post-steps:
            - *retrieve-junit
            - &notify-failure
              slack/notify:
                event: fail
                template: basic_fail_1
      - test-backend:
          <<: *test-config
      - publish-latest:
          context: shared-vars
          requires:
            - test-frontend
            - test-backend
          filters:
            branches:
              only: master
          post-steps:
            - *notify-failure
  release:
    jobs:
      - publish-tag:
          context: shared-vars
          filters:
            # CircleCI is so fucking dumb! https://discuss.circleci.com/t/workflow-job-with-tag-filter-being-run-for-every-commit/20762/3
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
          post-steps:
            - *notify-failure
