version: 2.1

orbs:
  node: circleci/node@4
  slack: circleci/slack@3

aliases:
  - &runner
    executor:
      name: node/default
      tag: lts
  - &size
    resource_class: small

jobs:
  lint:
    <<: *runner
    <<: *size
    steps:
      - checkout
      - &install-modules
        node/install-packages:
          include-branch-in-cache-key: false
          override-ci-command: npm ci --no-audit --prefer-offline
      - run:
          name: Lint (Prettier)
          command: npm run lint:prettier
      - run:
          name: Lint (ESLint)
          command: npm run lint:eslint -- --format junit --output-file reports/eslint/results.xml
      - &retrieve-junit
        store_test_results:
          path: reports
  test-frontend:
    <<: *runner
    <<: *size
    steps:
      - checkout
      - *install-modules
      - run:
          name: Test CRA
          command: npm run pretest && npm run test:nowatch:frontend -- -- --ci --runInBand --reporters=jest-junit --reporters=default
          environment:
            NODE_ENV: test
            JEST_JUNIT_OUTPUT_DIR: reports/jest-frontend
      - *retrieve-junit
      - slack/notify-on-failure
  test-backend:
    <<: *size
    docker:
      - image: cimg/node:lts
        environment:
          NODE_ENV: test
          DATABASE_URL: postgres://knex@localhost/blink
          REDIS_URL: redis://localhost
      - image: circleci/postgres:alpine-ram
        environment:
          POSTGRES_DB: blink
          POSTGRES_USER: knex
          POSTGRES_HOST_AUTH_METHOD: trust
      - image: circleci/redis:alpine
    steps:
      - checkout
      - *install-modules
      - run:
          name: Test Express
          command: npm run pretest && npm run test:nowatch:backend -- --ci --runInBand --reporters=jest-junit --reporters=default
          environment:
            JEST_JUNIT_OUTPUT_DIR: reports/jest-backend
            NODE_ENV: test
            LINK_TIMEOUT: 4 seconds
      - *retrieve-junit
      - slack/notify-on-failure
  publish-tag:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - &docker-login
        run:
          name: Login to GitHub Container Registry
          command: echo $GHCR_TOKEN | docker login ghcr.io -u JaneJeon --password-stdin
      - run:
          name: Build Docker image
          command: docker build -t "ghcr.io/janejeon/blink:$CIRCLE_TAG" .
      - run:
          name: Push Docker image
          command: docker push "ghcr.io/janejeon/blink:$CIRCLE_TAG"
  publish-latest:
    machine:
      image: ubuntu-2004:202107-02
    steps:
      - checkout
      - *docker-login
      - run:
          name: Build Docker image
          command: docker build -t "ghcr.io/janejeon/blink:latest" .
      - run:
          name: Push Docker image
          command: docker push "ghcr.io/janejeon/blink:latest"

workflows:
  build-and-test:
    jobs:
      - lint
      - test-frontend: &test-config
          context: shared-vars
          requires:
            - lint
      - test-backend:
          <<: *test-config
      - publish-latest:
          context: shared-vars
          requires:
            - test-frontend
            - test-backend
          filters:
            branches:
              only: master
  release:
    jobs:
      - publish-tag:
          context: shared-vars
          filters:
            # CircleCI is so fucking dumb! https://discuss.circleci.com/t/workflow-job-with-tag-filter-being-run-for-every-commit/20762/3
            branches:
              ignore: /.*/
            tags:
              only: /^v.*/
