# dynamic configuration
# see: https://doc.traefik.io/traefik/reference/dynamic-configuration/file/
tls:
  certificates:
    - certFile: /etc/traefik/localhost.cert.pem
      keyFile: /etc/traefik/localhost.key.pem

http:
  middlewares:
    https-302:
      redirectRegex:
        regex: ^http://(.*)
        replacement: 'https://${1}'
        permanent: false
    floc:
      headers:
        customResponseHeaders:
          Permissions-Policy: interest-cohort=()
